apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: game-of-life-front:latest
          imagePullPolicy: IfNotPresent  # <--- ADICIONE ESTA LINHA
          env:
            - name: VITE_BUILD_MODE
              value: "development"
          ports:
            - containerPort: 8080
---
# k8s/frontend-deployment.yaml

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 8080
      nodePort: 31073
